### ISSUE TITLE
Fix content problem on /year/2017/info/presenter-information/speakers-and-presenters.md

### ISSUE THREAD

**Issue by mhaley1979** [ieee-vgtc/ieeevis.org#223]
Q: why doesn’t the link to the file work? It is in ieeevis.org/attachments/vis_2017.ppt

Thanks.

**Comment by cscheid** [comment]
Because that's a static link to the _production_ site, and that file hasn't been pushed to production yet.

You want to use a site-relative link: use the url `/attachments/vis_2017.ppt`, so that when in the staging site, the browser points to `staging.ieeevis.org/attachments/vis_2017.ppt`, and when in the production site, the browser points to `ieeevis.org/attachments/vis_2017.ppt`

**Comment by mhaley1979** [comment]
ah, thanks, Carlos!
