### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by cscheid** [ieee-vgtc/ieeevis.org#337]
cc @tamaramunzner 

We need a location for ieeevis governance documents. This issue tracks the situation.

**Comment by tamaramunzner** [comment]
I would like the new coordination markdown doc and the updated bid
guidelines (in markup) posted before tue 8am welcome, ideally before mon
6:30am vec mtg. What do we have to do to make this happen? Are they already
up and available, then it's just a matter of adding the correct links in
the existing other pages that point to the old docs, and adding a menu item
on the left? or is this in limbo waiting for a decision on where to put the
folder?...

**Comment by cscheid** [comment]
They are available and live, just not on the sidebar. I’ll add the sidebar links at some point this morning.

**Comment by yelper** [comment]
We will copy the governance content to the new year so that it remains evergreen.  We will not accept deletions to this content (unless in cases of GDPR/leaking secrets) for reasons of preventing link rot.

Current location is https://github.com/ieee-vgtc/ieeevis.org/tree/vis2020/governance; these files are available via http://ieeevis.org/governance/ (e.g. http://ieeevis.org/governance/restructuring).
